### ISSUE TITLE
可以不可以添加一个 上传服务器啊api？

### ISSUE THREAD

**Issue by MasterBetter** [skooal/CocoaLogKit#2]

**Comment by apdevzhang** [comment]
你好，现在我们的伙伴全专用Swift了所以这个库暂时不再维护了，后期可能会出Swift版本。
你的问题我的理解是这样的，首先可以根据代码获取到存储在本地日志文件，当获取到日志文件本身之后该如何上传文件需要前端和后台再沟通了。

**Comment by apdevzhang** [comment]
close
